<template>
  <div class="control-section">
    <div class="tablediv" style="font-size:14px">
      <div class="rowdiv">
        <div class="celldiv">
          <table width="100%">
            <tbody>
              <tr>
                <td>
                  Click the button to view a PDF document generated by JavaScript PDF Library. Please note
                  that Adobe Reader or its equivalent is required to view the resultant document.
                </td>
              </tr>
              <tr>
                <td align="left">
                  <br />
                  <input id="bookmarkbtn" class="e-btn" value="Create Bookmarks" style="width: 160px; text-transform:capitalize" />
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div id="action-description">
    <p>
      This sample demonstrates how to add bookmark with the different style in the document. It is also possible to
      insert, remove, change text appearance, change destination and more from the PDF document.
    </p>
  </div>

  <div id="description">
    <p>More information about the bookmarks can be found in this documentation <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/bookmarks">section</a>.</p>
  </div>
</template>

<script lang="ts">
import { onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import {
  PdfDocument,
  PdfPage,
  PdfBrush,
  PdfFontFamily,
  PdfDestination,
  PdfBookmark,
  PdfStandardFont,
  Rectangle,
  PdfBookmarkBase
} from '@syncfusion/ej2-pdf';

export default {
  name: 'BookmarksSample',
  setup() {
    onMounted(() => {
      const btn = new Button();
      btn.appendTo('#bookmarkbtn');
      if (btn.element) (btn.element as HTMLButtonElement).onclick = () => generate();
    });

    function generate(): void {
      const document = new PdfDocument();
      for (let i = 1; i <= 3; i++) {
        const page: PdfPage = document.addPage();
        const chapterTitle = `Chapter ${i}`;
        drawTitle(page, chapterTitle, 10, 10, new PdfBrush({ r: 255, g: 0, b: 0 }));

        const bookmarks: PdfBookmarkBase = (document as any).bookmarks;
        const chapter: PdfBookmark = bookmarks.add(chapterTitle);
        chapter.destination = new PdfDestination(page, { x: 10, y: 10 });
        chapter.color = { r: 255, g: 0, b: 0 } as any;

        const sec1Title = `Section ${i}.1`;
        const sec2Title = `Section ${i}.2`;
        drawTitle(page, sec1Title, 30, 30, new PdfBrush({ r: 0, g: 255, b: 0 }));
        drawTitle(page, sec2Title, 30, 400, new PdfBrush({ r: 0, g: 255, b: 0 }));

        const section1: PdfBookmark = chapter.add(sec1Title);
        section1.destination = new PdfDestination(page, { x: 30, y: 30 });
        section1.color = { r: 0, g: 128, b: 0 } as any;

        const section2: PdfBookmark = chapter.add(sec2Title);
        section2.destination = new PdfDestination(page, { x: 30, y: 400 });
        section2.color = { r: 0, g: 128, b: 0 } as any;

        const subs1 = [
          { t: `Paragraph ${i}.1.1`, pt: { x: 50, y: 50 } },
          { t: `Paragraph ${i}.1.2`, pt: { x: 50, y: 150 } },
          { t: `Paragraph ${i}.1.3`, pt: { x: 50, y: 250 } }
        ];
        for (const s of subs1) {
          drawTitle(page, s.t, s.pt.x, s.pt.y, new PdfBrush({ r: 0, g: 0, b: 255 }));
          const b = section1.add(s.t);
          b.destination = new PdfDestination(page, s.pt);
          b.color = { r: 0, g: 0, b: 255 } as any;
        }

        const subs2 = [
          { t: `Paragraph ${i}.2.1`, pt: { x: 50, y: 420 } },
          { t: `Paragraph ${i}.2.2`, pt: { x: 50, y: 560 } },
          { t: `Paragraph ${i}.2.3`, pt: { x: 50, y: 680 } }
        ];
        for (const s of subs2) {
          drawTitle(page, s.t, s.pt.x, s.pt.y, new PdfBrush({ r: 0, g: 0, b: 255 }));
          const b = section2.add(s.t);
          b.destination = new PdfDestination(page, s.pt);
          b.color = { r: 0, g: 0, b: 255 } as any;
        }
      }
      document.save('Bookmarks.pdf');
      document.destroy();
    }

    function drawTitle(page: PdfPage, title: string, x: number, y: number, brush: PdfBrush) {
      const font = new PdfStandardFont(PdfFontFamily.helvetica, 10);
      const bounds: Rectangle = { x: x, y: y, width: 500, height: 20 } as any;
      page.graphics.drawString(title, font, bounds, brush);
    }

    return {};
  }
};
</script>

<style scoped>
.control-section { margin-bottom: 12px; }
.e-btn { width: 150px; text-transform: capitalize; }
#action-description, #description { margin-top: 12px; }
</style>
