<template>
  <div>
    <div class="control-section">
      <div class="tablediv" style="font-size:14px">
        <div class="rowdiv">
          <div class="celldiv">
            <table width="100%">
              <tbody>
                <tr>
                  <td>
                    Click the button to view a PDF document generated by JavaScript PDF Library. Please note
                    that Adobe Reader or its equivalent is required to view the resultant document.
                  </td>
                </tr>
                <tr>
                  <td align="left">
                    <br />
                    <input id="successbtn" class="e-btn" value="Generate PDF" style="width: 150px; text-transform:capitalize" />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div id="action-description">
      <p>
        This sample demonstrates how to list the content in <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/lists">ordered and unordered list</a>. The ordered list can be number or
        alphabets and the unordered list can be bullets, circles, and disks.
      </p>
    </div>
    <div id="description">
      <p>You can also create and format ordered and unordered lists in a PDF document, including custom markers, fonts, and nested structures.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import {
  PdfDocument,
  PdfBrush,
  PdfFontFamily,
  PdfFontStyle,
  PdfListItem,
  PdfListItemCollection,
  PdfOrderedList,
  PdfStringFormat,
  PdfUnorderedList,
  PdfUnorderedListStyle
} from '@syncfusion/ej2-pdf';

export default defineComponent({
  name: 'BulletsAndListsPdf',
  setup() {
    onMounted(() => {
      const button = new Button();
      button.appendTo('#successbtn');
      (button.element as HTMLElement).onclick = (): void => {
        createPdf();
      };
    });

    function createPdf(): void {
      const pdf = new PdfDocument();
      const page = pdf.addPage();

      const font1 = pdf.embedFont(PdfFontFamily.helvetica, 14, PdfFontStyle.bold);
      const font2 = pdf.embedFont(PdfFontFamily.helvetica, 12, PdfFontStyle.regular);
      const font3 = pdf.embedFont(PdfFontFamily.timesRoman, 10, PdfFontStyle.bold);
      const font4 = pdf.embedFont(PdfFontFamily.timesRoman, 10, PdfFontStyle.italic);
      const font5 = pdf.embedFont(PdfFontFamily.timesRoman, 10, PdfFontStyle.regular);

      page.graphics.drawString('List Features', font1, { x: 225, y: 10, width: 300, height: 100 }, new PdfBrush({ r: 0, g: 0, b: 139 }));
      page.graphics.drawString(
        'This sample demonstrates letious features of bullets and lists. A list can be ordered and Unordered. Essential PDF provides support for creating and formatting ordered and unordered lists.',
        font2,
        { x: 0, y: 50, width: page.graphics.clientSize.width, height: page.graphics.clientSize.height - 50 },
        new PdfBrush({ r: 0, g: 0, b: 0 })
      );

      const format = new PdfStringFormat();
      format.lineSpacing = 10;

      const collection = new PdfListItemCollection(['List of Essential Studio products', 'IO products']);
      const list = new PdfUnorderedList(collection, { format: format, font: font3, style: PdfUnorderedListStyle.disk, indent: 10, textIndent: 10 });

      const subList = new PdfOrderedList(new PdfListItemCollection(), { brush: new PdfBrush({ r: 0, g: 0, b: 0 }), indent: 20, font: font4, format: format });
      const products = ['Tools', 'Grid', 'Chart', 'Edit', 'Diagram', 'XlsIO', 'Grouping', 'Calculate', 'PDF', 'HTMLUI', 'DocIO'];
      products.forEach(function (s) {
        subList.items.add(new PdfListItem('Essential ' + s));
      });
      list.items.at(0).subList = subList;

      const subSubListCollection = new PdfListItemCollection([
        'Essential PDF: It is a .NET library with the capability to produce Adobe PDF files. It features a full-fledged object model for the easy creation of PDF files from any .NET language. It does not use any external libraries and is built from scratch in C#. It can be used on the server side (ASP.NET or any other environment) or with Windows Forms applications. Essential PDF supports many features for creating a PDF document. Drawing Text, Images, Shapes, etc can be drawn easily in the PDF document.',
        'Essential DocIO: It is a .NET library that can read and write Microsoft Word files. It features a full-fledged object model similar to the Microsoft Office COM libraries. It does not use COM interop and is built from scratch in C#. It can be used on systems that do not have Microsoft Word installed. Here are some of the most common questions that arise regarding the usage and functionality of Essential DocIO.',
        'Essential XlsIO: It is a .NET library that can read and write Microsoft Excel files (BIFF 8 format). It features a full-fledged object model similar to the Microsoft Office COM libraries. It does not use COM interop and is built from scratch in C#. It can be used on systems that do not have Microsoft Excel installed, making it an excellent reporting engine for tabular data.'
      ]);

      const SubsubList = new PdfUnorderedList(subSubListCollection, { brush: new PdfBrush({ r: 0, g: 0, b: 0 }), indent: 20, font: font5, format: format, style: PdfUnorderedListStyle.square });
      list.items.at(1).subList = SubsubList;

      list.draw(page, { x: 0, y: 130, width: page.graphics.clientSize.width, height: page.graphics.clientSize.height - 130 });

      pdf.save('BulletsAndLists.pdf');
      pdf.destroy();
    }

    return {};
  }
});
</script>