<template>
  <div class="control-section">
    <div style="font-size:14px">
      <table>
        <tbody>
          <tr>
            <td>
              Click the button to view a PDF document generated by JavaScript PDF Library. Please note
              that Adobe Reader or its equivalent is required to view the resultant document.
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="tablediv" style="font-size:14px; margin-top:20px;">
      <div class="card">
        <div class="card-title">Signature Settings</div>
        <div class="card-body">
          <div class="form-row">
            <label class="form-label">Cryptographic Standard:</label>
            <div class="form-group">
              <label><input type="radio" name="cryptoStandard" value="CMS" checked /> CMS</label>
              <label><input type="radio" name="cryptoStandard" value="CAdES" /> CAdES</label>
            </div>
          </div>
          <div class="form-row">
            <label class="form-label">Digest Algorithm:</label>
            <div class="form-group">
              <label><input type="radio" name="digestAlgo" value="SHA1" /> SHA1</label>
              <label><input type="radio" name="digestAlgo" value="SHA256" checked /> SHA256</label>
              <label><input type="radio" name="digestAlgo" value="SHA384" /> SHA384</label>
              <label><input type="radio" name="digestAlgo" value="SHA512" /> SHA512</label>
              <label><input type="radio" name="digestAlgo" value="RIPEMD160" /> RIPEMD160</label>
            </div>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-title">Sign new PDF document</div>
        <div class="card-body">
          <div class="form-row">
            <label class="form-label">Signature Type:</label>
            <div class="form-group">
              <label><input type="radio" name="signatureType" value="Standard" checked /> Standard</label>
              <label><input type="radio" name="signatureType" value="Author" /> Author</label>
            </div>
          </div>
          <button id="createSignBtn" class="e-btn" style="width: 160px; text-transform:capitalize">Create and Sign PDF</button>
        </div>
      </div>

      <div class="card">
        <div class="card-title">Sign existing PDF document</div>
        <div class="card-body">
          <div class="form-row">
            <label class="form-label" for="sourceFile">Source</label>
            <input id="sourceFile" class="file-input" type="file" accept=".pdf">
            <label for="sourceFile" class="e-btn file-btn">Choose File</label>
            <span id="sourceFileName" class="file-name">No file chosen</span>
          </div>
          <div class="form-row">
            <label class="form-label" for="certFile">Certificate</label>
            <input id="certFile" class="file-input" type="file" accept=".pfx,.p12">
            <label for="certFile" class="e-btn file-btn">Choose File</label>
            <span id="certFileName" class="file-name">No file chosen</span>
          </div>
          <div class="form-row">
            <label class="form-label" for="certPassword">Password</label>
            <input type="password" id="certPassword" placeholder="Password" />
          </div>
          <div class="form-row">
            <label class="form-label" for="reason">Reason</label>
            <input type="text" id="reason" placeholder="Reason" />
          </div>
          <div class="form-row">
            <label class="form-label" for="contact">Contact</label>
            <input type="text" id="contact" placeholder="Contact" />
          </div>
          <div class="form-row">
            <label class="form-label" for="location">Location</label>
            <input type="text" id="location" placeholder="Location" />
          </div>
          <button id="signExistingBtn" class="e-btn" style="width: 150px; text-transform:capitalize">Sign PDF</button>
        </div>
      </div>
    </div>
    <div id="action-description">
      <p>
        This sample demonstrates how to digitally sign the PDF document with the PFX certificate file. It is possible to digitally sign with X509 certificates such as .pfx files with private keys.
      </p>
    </div>
    <div id="description">
      <p>More information about the digital signature can be found in this documentation <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/digitalsignature">section</a>.</p>
    </div>
  </div>
</template>
<style scoped>
    input[type="radio"] {
        margin-top: 16px;
    }
    .row {
      display: flex;
      align-items: center;
      margin: 10px 0;
    }
    .control-section .file-input {
      position: absolute;
      width: 1px;
      height: 1px;
      padding: 0;
      margin: -1px;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
      border: 0;
    }
    .file-name {
      color: #6b7280;
    }
    .control-section {
        padding: 12px;
    }
    .card {
        border: 1px solid #ddd;
        border-radius: 4px;
        margin-bottom: 16px;
        background: #fff;
    }
    .card-title {
        font-weight: 600;
        padding: 10px 12px;
        border-bottom: 1px solid #eee;
        background: #f9f9f9;
    }
    .card-body {
        padding: 12px;
    }
    .form-row {
        display: flex;
        align-items: center;
        gap: 12px;
        margin-bottom: 10px;
        flex-wrap: wrap;
    }
    .form-label {
        min-width: 200px;
        color: #333;
    }
    .form-group label {
        margin-right: 16px;
    }
    input[type="text"],
    input[type="password"],
    input[type="file"] {
        width: 300px;
        max-width: 100%;
    }
    .form-row .e-control.e-textbox,
    .form-row .e-control.e-filled {
      width: 300px !important;
      max-width: 100% !important;
      box-sizing: border-box;
      height: 36px !important;
      padding: 6px 10px !important;
      font-size: 14px !important;
      line-height: normal !important;
      border-radius: 4px !important;
    }
    .form-row .e-control.e-textbox .e-input,
    .form-row .e-control.e-filled .e-input {
      width: 100% !important;
      box-sizing: border-box;
      height: 100% !important;
      padding: 0 8px !important;
    }
    .form-row input[type="text"],
    .form-row input[type="password"] {
      height: 36px;
      padding: 6px 10px;
      font-size: 14px;
      line-height: normal;
      box-sizing: border-box;
    }
    .e-btn:disabled {
        opacity: 0.6;
        cursor: not-allowed;
    }
</style>
<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import { TextBox } from '@syncfusion/ej2-inputs';
import { PdfDocument, PdfSignatureField, PdfSignature, CryptographicStandard, DigestAlgorithm, PdfBitmap } from '@syncfusion/ej2-pdf';

export default defineComponent({
  name: 'DigitalSignaturePdf',
  setup() {
    onMounted(() => {
      const createBtn = new Button();
      createBtn.appendTo('#createSignBtn');
      const signBtn = new Button({}, '#signExistingBtn');
      (createBtn.element as HTMLElement).onclick = () => createAndSignPdf();
      (signBtn.element as HTMLElement).onclick = () => signExistingPdf();
      // Initialize EJ2 TextBox components for inputs using demo-like features
      new TextBox({ cssClass: 'e-filled', placeholder: 'Password', type: 'password', width: '300px', showClearButton: false }, '#certPassword');
      new TextBox({ cssClass: 'e-filled', placeholder: 'Reason', width: '300px', showClearButton: true }, '#reason');
      new TextBox({ cssClass: 'e-filled', placeholder: 'Contact', width: '300px', showClearButton: true }, '#contact');
      new TextBox({ cssClass: 'e-filled', placeholder: 'Location', width: '300px', showClearButton: true }, '#location');
      const srcInput = document.getElementById('sourceFile') as HTMLInputElement | null;
      const certInput = document.getElementById('certFile') as HTMLInputElement | null;
      const srcNameSpan = document.getElementById('sourceFileName') as HTMLElement | null;
      const certNameSpan = document.getElementById('certFileName') as HTMLElement | null;
      if (srcInput && srcNameSpan) {
          srcInput.addEventListener('change', () => {
              const f = srcInput.files && srcInput.files[0];
              srcNameSpan.textContent = f ? f.name : 'No file chosen';
          });
      }
      if (certInput && certNameSpan) {
          certInput.addEventListener('change', () => {
              const f = certInput.files && certInput.files[0];
              certNameSpan.textContent = f ? f.name : 'No file chosen';
          });
      }
      (window as any).createAndSignPdf = createAndSignPdf;
      (window as any).signExistingPdf = signExistingPdf;
    });

    function signPdf(
      pdfBytes: Uint8Array,
      options: {
        bounds?: { x?: number; y?: number; width?: number; height?: number };
        fieldName?: string;
        crypto?: string | null;
        digest?: string | null;
        pfxData: Uint8Array;
        password: string;
        contact?: string;
        location?: string;
        reason?: string;
        logoBytes?: Uint8Array;
        logoRect?: { x?: number; y?: number; width?: number; height?: number };
        outputName: string;
        author?: boolean;
      }
    ): void {
      const pdf = new PdfDocument(pdfBytes);
      const page = pdf.getPage(0);
      const b = options.bounds ?? {};
      const sigX = typeof b.x === 'number' ? b.x : 20;
      const sigY = typeof b.y === 'number' ? b.y : 20;
      const sigW = typeof b.width === 'number' ? b.width : 200;
      const sigH = typeof b.height === 'number' ? b.height : 100;

      const signatureField = new PdfSignatureField(page, options.fieldName || 'Signature', { x: sigX, y: sigY, width: sigW, height: sigH });

      var sigOptions = {
        cryptographicStandard: mapCryptoStandard(options.crypto ?? 'CMS'),
        digestAlgorithm: mapDigestAlgorithm(options.digest ?? 'SHA256'),
        contactInfo: options.contact || '',
        locationInfo: options.location || '',
        reason: options.reason || ''
      } as any;

      if (options.author === true) {
        (sigOptions as any).certify = true;
      }

      const signature = PdfSignature.create(options.pfxData, options.password, sigOptions);
      signatureField.setSignature(signature);
      pdf.form.add(signatureField);

      if (options.logoBytes) {
        const app = signatureField.getAppearance();
        const lr = options.logoRect ?? {};
        const lx = typeof lr.x === 'number' ? lr.x : 20;
        const ly = typeof lr.y === 'number' ? lr.y : 20;
        const lw = typeof lr.width === 'number' ? lr.width : 120;
        const lh = typeof lr.height === 'number' ? lr.height : 50;
        const logoBmp = new PdfBitmap(options.logoBytes);
        app.normal.graphics.drawImage(logoBmp, { x: lx, y: ly, width: lw, height: lh });
      }

      pdf.save(options.outputName);
      pdf.destroy();
    }

    function getSelectedRadio(name: string): string | null {
      const el = document.querySelector(`input[name="${name}"]:checked`) as HTMLInputElement | null;
      return el ? el.value : null;
    }

    function mapCryptoStandard(val: string | null): CryptographicStandard {
      return val === 'CAdES' ? CryptographicStandard.cades : CryptographicStandard.cms;
    }

    function mapDigestAlgorithm(val: string | null): DigestAlgorithm {
      switch (val) {
        case 'SHA1':
          return DigestAlgorithm.sha1;
        case 'SHA384':
          return DigestAlgorithm.sha384;
        case 'SHA512':
          return DigestAlgorithm.sha512;
        case 'RIPEMD160':
          return DigestAlgorithm.ripemd160;
        default:
          return DigestAlgorithm.sha256;
      }
    }

    async function readFromPdfResources(fileName: string): Promise<Uint8Array> {
      const res = await fetch(fileName);
      if (!res.ok) throw new Error(`Failed to fetch ${fileName}: ${res.status} ${res.statusText}`);
      const buf = await res.arrayBuffer();
      return new Uint8Array(buf);
    }

    async function createAndSignPdf(): Promise<void> {
      const crypto = getSelectedRadio('cryptoStandard');
      const digest = getSelectedRadio('digestAlgo');
      const sigType = getSelectedRadio('signatureType');
      const [pdfBytes, pfxBytes, logoBytes] = await Promise.all([
        readFromPdfResources('https://cdn.syncfusion.com/content/pdf-resources/pdf-succinctly.pdf'),
        readFromPdfResources('https://cdn.syncfusion.com/content/pdf-resources/PDF.pfx'),
        readFromPdfResources('https://cdn.syncfusion.com/content/pdf-resources/logo.png')
      ]);

      signPdf(pdfBytes, {
        crypto,
        digest,
        pfxData: pfxBytes,
        password: 'password123',
        contact: 'johndoe@owned.us',
        location: 'Honolulu, Hawaii',
        reason: sigType === 'Author' ? 'I am author of this document.' : 'Approved.',
        logoBytes,
        outputName: 'SignedPDF.pdf',
        author: sigType === 'Author'
      });
    }

    function ensureNoteHost(): HTMLDivElement {
      let host = document.getElementById('noteMessage') as HTMLDivElement | null;
      if (!host) {
        host = document.createElement('div');
        host.id = 'noteMessage';
        host.style.display = 'none';
        host.style.color = '#b00020';
        host.style.fontWeight = '600';
        host.style.margin = '8px 0';
        host.setAttribute('role', 'alert');
        host.setAttribute('aria-live', 'assertive');
        const controlSection = document.querySelector('.control-section') as HTMLElement | null || document.body;
        controlSection.insertBefore(host, controlSection.firstChild);
      }
      return host;
    }

    function showNote(msg: string) {
      const noteEl = ensureNoteHost();
      noteEl.textContent = msg;
      noteEl.style.display = 'block';
      try { noteEl.scrollIntoView({ behavior: 'smooth', block: 'center' }); } catch { }
    }

    function hideNote() {
      const noteEl = document.getElementById('noteMessage') as HTMLDivElement | null;
      if (noteEl) noteEl.style.display = 'none';
    }

    async function signExistingPdf(): Promise<void> {
      const crypto = getSelectedRadio('cryptoStandard');
      const digest = getSelectedRadio('digestAlgo');
      const sourceInput = document.getElementById('sourceFile') as HTMLInputElement | null;
      const certInput = document.getElementById('certFile') as HTMLInputElement | null;
      const passwordEl = document.getElementById('certPassword') as HTMLInputElement | null;
      const reasonEl = document.getElementById('reason') as HTMLInputElement | null;
      const contactEl = document.getElementById('contact') as HTMLInputElement | null;
      const locationEl = document.getElementById('location') as HTMLInputElement | null;
      const password = (passwordEl?.value || '').trim();
      const reason = (reasonEl?.value || '').trim();
      const contact = (contactEl?.value || '').trim();
      const location = (locationEl?.value || '').trim();
      const hasSource = !!sourceInput?.files?.length;
      const hasCert = !!certInput?.files?.length;
      const allOk = hasSource && hasCert && password && reason && contact && location;
      if (!allOk) {
        showNote('NOTE: Fill all fields and then create PDF');
        return;
      }
      hideNote();
      const sourceFile = sourceInput!.files![0];
      const certFile = certInput!.files![0];
      try {
        const [srcBuf, pfxBuf, logoBytes] = await Promise.all([
          sourceFile.arrayBuffer(),
          certFile.arrayBuffer(),
          readFromPdfResources('https://cdn.syncfusion.com/content/pdf-resources/logo.png')
        ]);
        const pdfBytes = srcBuf instanceof Uint8Array ? srcBuf : new Uint8Array(srcBuf);
        const pfxBytes = pfxBuf instanceof Uint8Array ? pfxBuf : new Uint8Array(pfxBuf);
        signPdf(pdfBytes, {
          crypto,
          digest,
          pfxData: pfxBytes,
          password,
          contact,
          location,
          reason,
          logoBytes,
          outputName: 'SignedPDF.pdf'
        });
      } catch (err: any) {
        showNote(err?.message || 'Error while signing existing PDF.');
      }
    }

    return {};
  }
});
</script>
