<template>
  <div>
    <div class="control-section">
      <div class="tablediv" style="font-size:14px">
        <div class="rowdiv">
          <div class="celldiv">
            <table width="100%">
              <tbody>
                <tr>
                  <td>
                    Click the button to view a PDF document generated by JavaScript PDF library. Please note
                    that Adobe Reader or its equivalent is required to view the resultant document.
                  </td>
                </tr>
                <tr>
                  <td align="left">
                    <br />
                    <button id="documentbtn" class="e-btn" style="width:150px; text-transform:capitalize">
                      Generate PDF
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div id="action-description">
      <p>
        This sample demonstrates adding PDF document properties such as title, author, keyword, subject, and producer etc.
      </p>
    </div>
    <div id="description">
      <p>More information about the document settings can be found in this documentation <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/pdf-document#adding-the-document-settings">section</a>.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import { PdfDocument, PdfBrush, PdfFontFamily, PdfFontStyle } from '@syncfusion/ej2-pdf';

export default defineComponent({
  name: 'DocumentSettingsPdf',
  setup() {
    onMounted(() => {
      const btn = new Button({}, '#documentbtn');
      (btn.element as HTMLElement).onclick = (): void => {
        // Create a new PDF document
        const pdf = new PdfDocument();
        // Set document information
        const now = new Date();
        pdf.setDocumentInformation({
          author: 'Syncfusion',
          creationDate: now,
          modificationDate: now,
          creator: 'Essential PDF',
          keywords: 'PDF',
          subject: 'Document information DEMO',
          title: 'Syncfusion JavaScript PDF Library Example',
          producer: 'Syncfusion PDF'
        });
        // Add a page and draw text
        const page = pdf.addPage();
        const g = page.graphics;
        const boldFont = pdf.embedFont(PdfFontFamily.helvetica, 12, PdfFontStyle.bold);
        const regularFont = pdf.embedFont(PdfFontFamily.helvetica, 10, PdfFontStyle.regular);
        const black = new PdfBrush({ r: 0, g: 0, b: 0 });
        g.drawString('Document Properties', boldFont, { x: 10, y: 10, width: 520, height: 20 }, black);
        const formattedDate = now.toLocaleString('en-US', {
          month: 'numeric',
          day: 'numeric',
          year: 'numeric',
          hour: 'numeric',
          minute: 'numeric',
          second: 'numeric',
          hour12: true
        });
        let y = 50;
        const line = (text: string) => {
          g.drawString(text, regularFont, { x: 10, y, width: 520, height: 16 }, black);
          y += 20;
        };
        line('Title: Syncfusion JavaScript PDF Library Example');
        line('Author: Syncfusion');
        line('Subject: Document information DEMO');
        line('Keywords: PDF');
        line('Created: ' + formattedDate);
        line('Modified: ' + formattedDate);
        line('Application: Essential PDF');
        // Save and download the document
        pdf.save('DocPropertiesAndXml.pdf');
        pdf.destroy();
      };
    });

    return {};
  }
});
</script>