<template>
  <div>
    <div class="control-section">
      <div class="tablediv" style="font-size:14px">
        <text class="rowdiv">
          Click the button to view a PDF document generated by JavaScript PDF Library. Please note that Microsoft Word or its equivalent is required to view the resultant document.
        </text>
        <div class="tablediv" style="font-size:14px">
          <div class="rowdiv">
            <div class="celldiv">
              <table style="width:100%">
                <tbody>
                  <tr>
                    <td align="left">
                      <br />
                      <button id="viewtemplatebtn" style="width: 150px; text-transform:capitalize">View Template</button>
                      <button id="extractbtn" style="width: 150px; text-transform:capitalize; margin-left: 8px">Extract Image</button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="action-description" style="margin-top: 10px">
      <p>
        This sample demonstrates how to extract images from the PDF document. The extracted images can be saved into any
        raster image format.
      </p>
    </div>

    <div id="description" style="margin-top: 10px">
      <p>This feature will be used to extract the images from the PDF document. More information about the image extraction can be found in this documentation <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/image-extraction">section</a>.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import { PdfDocument } from '@syncfusion/ej2-pdf';
import { PdfDataExtractor } from '@syncfusion/ej2-pdf-data-extract';

export default defineComponent({
  name: 'ExtractImagePdf',
  setup() {
    onMounted(() => {
      const viewBtn = new Button();
      viewBtn.appendTo('#viewtemplatebtn');
      const extractBtn = new Button();
      extractBtn.appendTo('#extractbtn');

      extractBtn.element.onclick = async (): Promise<void> => {
        try {
          // Fetch the template PDF bytes from the remote URL with cache disabled
          const pdfBytes = await readFromPdfResources(templateUrl);
          // Create a PdfDocument instance from the fetched bytes
          const pdf = new PdfDocument(pdfBytes);
          // Extract images across the full page range
          const extractor = new PdfDataExtractor(pdf, canvasRenderCallback);
          const images = await extractor.extractImages({ startPageIndex: 0, endPageIndex: pdf.pageCount - 1 });
          if (images && images.length > 0) {
            const first = images[0];
            const blob = new Blob([first.data], { type: 'image/jpeg' });
            downloadBlob(blob, outputImageName);
          } else {
            // eslint-disable-next-line no-console
            console.warn('No images found in the document.');
          }
          // Destroy the document instance
          pdf.destroy();
        } catch (err) {
          // eslint-disable-next-line no-console
          console.error('Extract Image failed:', err);
        }
      };

      viewBtn.element.onclick = async (): Promise<void> => {
        try {
          const pdfBytes = await readFromPdfResources(templateUrl);
          downloadBlob(new Blob([pdfBytes], { type: 'application/pdf' }), 'ImageTemplate.pdf');
        } catch (err) {
          // eslint-disable-next-line no-console
          console.error('View Template failed:', err);
        }
      };
    });

    return {};
  }
});

const templateUrl = 'https://cdn.syncfusion.com/content/pdf-resources/image-template.pdf';
const outputImageName = 'Sample.jpg';

async function readFromPdfResources(url: string): Promise<Uint8Array> {
  const res = await fetch(url, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  const buf = await res.arrayBuffer();
  return new Uint8Array(buf);
}

function downloadBlob(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function canvasRenderCallback(): any {
  const canvas = document.createElement('canvas');
  return { canvas: canvas, applicationPlatform: undefined };
}

</script>