<template>
  <div>
    <div class="control-section">
      <div class="tablediv" style="font-size:14px">
        <div class="rowdiv">
          <div class="celldiv">
            <table width="100%">
              <tbody>
                <tr>
                  <td>
                    Click the button to view a PDF document generated by JavaScript PDF Library. Please note that Adobe Reader or its equivalent is required to view the resultant document.
                  </td>
                </tr>
                <tr>
                  <td align="left">
                    <br />
                    <input id="hellowbtn" class="e-btn" value="Generate PDF" style="width: 150px; text-transform:capitalize" />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div id="action-description">
      This sample demonstrates the creation of simple PDF document. It draws the string 'Hello world!!!' in the
      desired location using the <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/text#draw-text-using-standard-fonts">PDF standard font</a>.
    </div>

    <div id="description">
      <p>
        It is also possible to draw different language of text with different fonts using <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/text#draw-text-using-truetype-fonts">True Type fonts</a> and <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/text#draw-text-using-cjk-fonts">CJK fonts</a>.
      </p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import { PdfDocument, PdfBrush, PdfFontFamily, PdfFontStyle } from '@syncfusion/ej2-pdf';

export default defineComponent({
  name: 'HelloWorldPdf',
  setup() {
    onMounted(() => {
      const button = new Button();
      button.appendTo('#hellowbtn');
      (button.element as HTMLElement).onclick = (): void => {
        // Create a new PDF document
        const pdf = new PdfDocument();
        // Add a new page
        const page = pdf.addPage();
        // Access graphics of the page
        const graphics = page.graphics;
        // Create a new PDF standard font
        const font = pdf.embedFont(PdfFontFamily.helvetica, 36, PdfFontStyle.regular);
        // Create a new black brush
        const brush = new PdfBrush({ r: 0, g: 0, b: 0 });
        // Draw the text
        graphics.drawString('Hello World!!!', font, { x: 20, y: 20, width: graphics.clientSize.width - 20, height: 60 }, brush);
        // Save and download PDF
        pdf.save('Sample.pdf');
        // Destroy the PDF document instance
        pdf.destroy();
      };
    });

    return {};
  }
});
</script>
