<template>
  <div>
    <div class="control-section">
      <div class="tablediv" style="font-size:14px">
        <div class="rowdiv">
          <div class="celldiv">
            <table width="100%">
              <tbody>
                <tr>
                  <td>
                    Click the button to view a PDF document generated by JavaScript PDF Library. Please note
                    that Adobe Reader or its equivalent is required to view the resultant document.
                  </td>
                </tr>
                <tr>
                  <td align="left">
                    <br />
                    <input id="generatebtn" class="e-btn" value="Generate PDF" style="width: 150px; text-transform:capitalize" />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div id="action-description" style="margin-top: 10px">
      <p>This sample demonstrates insertion of JPEG and PNG images in the PDF document.</p>
    </div>
    <div id="description" style="margin-top: 10px">
      <p>It is also possible to rotate and paginate the images in the PDF document. More information about the images can be found in this documentation <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/images">section</a>.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import { PdfDocument, PdfPage, PdfGraphics, PdfBrush, PdfFont, PdfFontFamily, PdfFontStyle, PdfBitmap } from '@syncfusion/ej2-pdf';

export default defineComponent({
  name: 'ImageInsertionPdf',
  setup() {
    onMounted(() => {
      const generateBtn = new Button();
      generateBtn.appendTo('#generatebtn');
      (generateBtn.element as HTMLElement).onclick = async (): Promise<void> => {
        try {
          const [jpgBytes, pngBytes] = await Promise.all([fetchAsUint8Array(jpeg), fetchAsUint8Array(png)]);

          const document: PdfDocument = new PdfDocument();
          const page: PdfPage = document.addPage();
          const g: PdfGraphics = page.graphics;

          const font: PdfFont = document.embedFont(PdfFontFamily.helvetica, 12, PdfFontStyle.bold);
          const blueBrush: PdfBrush = new PdfBrush({ r: 0, g: 0, b: 255 });

          g.drawString('JPEG Image', font, { x: 0, y: 40, width: 100, height: 100 }, blueBrush);
          const jpgImage: PdfBitmap = new PdfBitmap(jpgBytes);
          g.drawImage(jpgImage, { x: 0, y: 70, width: 515, height: 215 });

          g.drawString('PNG Image', font, { x: 0, y: 355, width: 100, height: 100 }, blueBrush);
          const pngImage: PdfBitmap = new PdfBitmap(pngBytes);
          g.drawImage(pngImage, { x: 0, y: 365, width: 199, height: 300 });

          document.save(outpt);
          document.destroy();
        } catch (err) {
          // eslint-disable-next-line no-console
          console.error('Generate PDF failed:', err);
        }
      };
    });

    return {};
  }
});

const jpeg = 'https://cdn.syncfusion.com/content/pdf-resources/xamarin-jpeg.jpg';
const png = 'https://cdn.syncfusion.com/content/pdf-resources/xamarin-png.png';
const outpt = 'Images.pdf';

async function fetchAsUint8Array(url: string): Promise<Uint8Array> {
  const res = await fetch(url, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  const buf = await res.arrayBuffer();
  return new Uint8Array(buf);
}
</script>
