<template>
	<div class="control-section">
		<div class="tablediv">
			<div class="rowdiv">
				<div class="celldiv">
					<table width="100%">
						<tbody>
							<tr>
								<td>
									Click the button to view a PDF document generated by JavaScript PDF Library. Please note
									that Adobe Reader or its equivalent is required to view the resultant document.
								</td>
							</tr>
							<tr>
								<td align="left">
									<br />
									<input id="layerbtn" class="e-btn" value="Generate PDF" />
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

	<div id="action-description">
		<p>
			This sample demonstrates adding layers (Optional Content Group) with different shapes in the PDF
			document. The Syncfusion JavaScript PDF library also supports creating, merging, and toggling the layers.
		</p>
	</div>

	<div id="description">
		<p>
			This feature can be used in CAD drawings, maps, layered artworks, and multi-language documents. More information about the layers can be found in this documentation <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/layers">section</a>.
		</p>
	</div>
</template>

<script lang="ts">
import { onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import {
	PdfDocument,
	PdfPageSettings,
	PdfMargins,
	PdfPage,
	PdfGraphics,
	PdfBrush,
	PdfPen,
	PdfFontFamily,
	PdfStandardFont
} from '@syncfusion/ej2-pdf';

export default {
	name: 'LayersSample',
	setup() {
		onMounted(() => {
			const button: Button = new Button();
			button.appendTo('#layerbtn');
			(button.element as HTMLButtonElement).onclick = (): void => {
				const doc = new PdfDocument();
				// Create page settings
				const settings = new PdfPageSettings();
				settings.size = { width: 350, height: 300 } as any;
				settings.margins = new PdfMargins(0);
				const page: PdfPage = doc.addPage(settings);
				// Heading
				const font = new PdfStandardFont(PdfFontFamily.helvetica, 16);
				const darkBlueBrush = new PdfBrush({ r: 0, g: 0, b: 139 });
				page.graphics.drawString('Layers', font, { x: 150, y: 10, width: 100, height: 100 }, darkBlueBrush);
				// ---------- Layer 1 ----------
				const layer1 = doc.layers.add('Layer1');
				const g1: PdfGraphics = layer1.createGraphics(page);
				g1.translateTransform({ x: 100, y: 60 });
				const rect = { x: 0, y: 0, width: 50, height: 50 } as any;
				let pen = new PdfPen({ r: 255, g: 0, b: 0 }, 50);
				// drawArc using pen
				g1.drawArc(rect, 360, 360, pen);
				pen = new PdfPen({ r: 0, g: 0, b: 255 }, 30);
				g1.drawArc(rect, 360, 360, pen);
				pen = new PdfPen({ r: 255, g: 255, b: 0 }, 20);
				g1.drawArc(rect, 360, 360, pen);
				pen = new PdfPen({ r: 0, g: 128, b: 0 }, 10);
				g1.drawArc(rect, 360, 360, pen);
				// ---------- Layer 2 ----------
				const layer2 = doc.layers.add('Layer2');
				const g2: PdfGraphics = layer2.createGraphics(page);
				g2.translateTransform({ x: 100, y: 180 });
				pen = new PdfPen({ r: 255, g: 0, b: 0 }, 50);
				g2.drawArc(rect, 360, 360, pen);
				pen = new PdfPen({ r: 0, g: 0, b: 255 }, 30);
				g2.drawArc(rect, 360, 360, pen);
				pen = new PdfPen({ r: 255, g: 255, b: 0 }, 20);
				g2.drawArc(rect, 360, 360, pen);
				pen = new PdfPen({ r: 0, g: 128, b: 0 }, 10);
				g2.drawArc(rect, 360, 360, pen);
				// ---------- Layer 3 ----------
				const layer3 = doc.layers.add('Layer3');
				const g3: PdfGraphics = layer3.createGraphics(page);
				g3.translateTransform({ x: 160, y: 120 });
				pen = new PdfPen({ r: 255, g: 0, b: 0 }, 50);
				g3.drawArc(rect, -60, 60, pen);
				pen = new PdfPen({ r: 0, g: 0, b: 255 }, 30);
				g3.drawArc(rect, -60, 60, pen);
				pen = new PdfPen({ r: 255, g: 255, b: 0 }, 20);
				g3.drawArc(rect, -60, 60, pen);
				pen = new PdfPen({ r: 0, g: 128, b: 0 }, 10);
				g3.drawArc(rect, -60, 60, pen);
				doc.save('Layers.pdf');
				doc.destroy();
			};
		});
		return {};
	}
};
</script>

<style scoped>
.tablediv { font-size: 14px; }
.celldiv { padding: 8px; }
#action-description, #description { margin-top: 12px; }
.e-btn { width: 150px; text-transform: capitalize; }
</style>

