<template>
  <div class="control-section">
    <div class="tablediv" style="font-size:14px">
      Click the button to view a PDF document generated by JavaScript PDF Library. Please note
      that Adobe Reader or its equivalent is required to view the resultant document.
    </div>
    <br />
    <div class="button-section">
      <div id="button-control">
        <div class="row" style="gap: 12px; align-items: center;">
          <div>
          <button style="margin-left: 15px" id="mergebtn" class="e-btn">Merge PDFs</button>
          </div>
        </div>
      </div>
    </div>

    <div id="action-description" style="margin-top: 10px">
      <p>This sample demonstrates how to merge two different PDF documents into a single PDF document. It is also possible to import selective pages to the PDF document.</p>
    </div>
    <div id="description" style="margin-top: 10px">
      <p>This feature can be used to assemble PDF documents for printing, electronic distribution, and bundle PDF for archiving. More information about the merge of PDF documents can be found in this documentation <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/merge-document">section</a>.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import { PdfDocument, PdfPageImportOptions } from '@syncfusion/ej2-pdf';

export default defineComponent({
  name: 'MergeDocuments',
  setup() {
    onMounted(() => {
      const mergeBtn = new Button({}, '#mergebtn');
      if (mergeBtn && mergeBtn.element) (mergeBtn.element as HTMLButtonElement).onclick = async () => {
        try {
          const pdfBytes = await fetchAsUint8Array(templateUrl);
          const doc1 = new PdfDocument(pdfBytes as any);
          const doc2 = new PdfDocument(pdfBytes as any);
          doc1.importPageRange(doc2, 0, (doc2 as any).pageCount - 1);
          doc1.save(outputPdfName);
          doc1.destroy();
          doc2.destroy();
        } catch (err) {
          console.error('Merge PDFs failed:', err);
        }
      };
    });
    return {};
  }
});

const templateUrl = 'https://cdn.syncfusion.com/content/pdf-resources/pdf-succinctly.pdf';
const outputPdfName = 'MergedPDF.pdf';

async function fetchAsUint8Array(url: string): Promise<Uint8Array> {
  const res = await fetch(url, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  const buf = await res.arrayBuffer();
  return new Uint8Array(buf);
}
</script>

<style scoped>
  .opt-label { display: inline-flex; gap: 8px; align-items: center; margin-top: 10px; margin-left: 8px; }
  .e-btn { width: 150px; text-transform: capitalize; margin-top: 10px; margin-left: 8px; }
  #action-description, #description { margin-top: 10px; }
</style>
