<template>
  <div class="control-section">
    <div class="form-container">
      <label class="form-label" for="ps">Page Size :</label>
      <select id="ps">
        <option>Letter</option>
        <option>Legal</option>
        <option>A3</option>
        <option selected>A4</option>
        <option>A5</option>
        <option>B4</option>
        <option>B5</option>
      </select>

      <label class="form-label" for="po">Page Orientation :</label>
      <select id="po">
        <option selected>Portrait</option>
        <option>Landscape</option>
      </select>

      <label class="form-label" for="pm">Page Margin :</label>
      <select id="pm">
        <option selected>No margin</option>
        <option>Small</option>
        <option>Large</option>
      </select>

      <label class="form-label" for="pr">Page Rotation :</label>
      <select id="pr">
        <option selected>0</option>
        <option>90</option>
        <option>180</option>
        <option>270</option>
      </select>

      <label class="form-label">Pages Count :</label>
      <div class="pages-inline">
        <input type="text" readonly id="pageCount" value="1" />
        <button id="addPage" type="button">Add Page</button>
      </div>
    </div>
    <br />
    <br />
    <div>
      <p>
        Click the button to view a PDF document generated by JavaScript PDF Library. Please note that Adobe Reader or its
        equivalent is required to view the resultant document.
      </p>
    </div>
    <div class="actions">
      <button id="normalbtn">Generate PDF</button>
    </div>
    <div id="action-description">
      <p>
        This sample demonstrates adding pages with different settings such as rotation, orientation and page size.
      </p>
    </div>
    <div id="description">
      <p>It is also possible to add or insert pages and sections, remove pages, rearrange pages, and more. More information about the pages and sections can be found in this documentation <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/pdf-pages">section</a>.</p>  
    </div>
  </div>
</template>
<style scoped>
  body {
    font-family: Arial, sans-serif;
    font-size: 14px;
    margin: 24px;
    color: #333;
  }
  .control-section {
    max-width: none;
  }
  .control-section p {
    margin-bottom: 16px;
  }
  .form-container {
    display: grid;
    grid-template-columns: 180px auto;
    column-gap: 12px;
    row-gap: 12px;
    align-items: center;
  }
  .form-label {
    text-align: left;
    white-space: nowrap;
  }
  select,
  input[type="text"] {
    width: 220px;
    padding: 6px;
    font-size: 14px;
    box-sizing: border-box;
  }
  .pages-inline {
    display: flex;
    gap: 8px;
    align-items: center;
  }
  .pages-inline input[type="text"] {
    width: 60px;
    text-align: center;
  }
  .apply-transition {
    margin-top: 20px;
    display: flex;
    align-items: center;
    gap: 8px;
  }
  .actions {
    margin-top: 16px;
  }
  button {
    padding: 6px 12px;
    font-size: 14px;
    cursor: pointer;
  }
  .apply-transition input[type="checkbox"] {
    width: 20px;
    height: 20px;
    transform: scale(0.75);
    cursor: pointer;
  }
</style>
<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import {
  PdfDocument,
  PdfPageSettings,
  PdfMargins,
  PdfPen,
  PdfBrush,
  PdfFontFamily,
  PdfFontStyle,
  PdfPageOrientation,
  PdfRotationAngle
} from '@syncfusion/ej2-pdf';

export default defineComponent({
  name: 'PageSettingsPdf',
  setup() {
    onMounted(() => {
      const genBtn = new Button({}, '#normalbtn');
      const addBtn = new Button({}, '#addPage');

      const addButton = document.getElementById('addPage') as HTMLButtonElement | null;
      const pageCountEl = document.getElementById('pageCount') as HTMLInputElement | null;
      if (addButton && pageCountEl) {
        addButton.addEventListener('click', () => {
          const current = parseInt(pageCountEl.value || '1', 10);
          pageCountEl.value = String(Math.max(1, current + 1));
        });
      }
      if (genBtn && genBtn.element) {
        (genBtn.element as HTMLButtonElement).onclick = () => createPdf();
      }
    });

    function createPdf(): void {
      const { ps, po, pm, pr, pageCount } = readUI();
      const settings = new PdfPageSettings();
      const size = getPageSize(ps);
      settings.size = size as any;
      settings.orientation = po === 'Portrait' ? PdfPageOrientation.portrait : PdfPageOrientation.landscape;
      settings.rotation = getRotationAngle(String(pr));
      settings.margins = new PdfMargins(getMargin(pm));

      const pdf = new PdfDocument();
      const pen = new PdfPen({ r: 0, g: 0, b: 0 }, 6);
      const lightGreenBrush = new PdfBrush({ r: 144, g: 238, b: 144 });
      const textBrush = new PdfBrush({ r: 0, g: 0, b: 0 });
      const footerFont = pdf.embedFont(PdfFontFamily.helvetica, 16, PdfFontStyle.regular);

      for (let i = 0; i < pageCount; i++) {
        const page = pdf.addPage(settings);
        const g = page.graphics;
        const client = g.clientSize;
        g.drawRectangle({ x: 0, y: 0, width: client.width, height: client.height }, lightGreenBrush);
        g.drawLine(pen, { x: 0, y: 100 }, { x: Math.min(300, client.width), y: 100 });
        const footerText = `Page ${i + 1} of ${pageCount}`;
        g.drawString(footerText, footerFont, { x: client.width - 150, y: client.height - 40, width: 140, height: 30 }, textBrush);
      }

      pdf.save('PageSettings.pdf');
      pdf.destroy();
    }

    function getPageSize(name: string) {
      const PAGE_SIZES: Record<string, { width: number; height: number }> = {
        Letter: { width: 612, height: 792 },
        Legal: { width: 612, height: 1008 },
        A3: { width: 842, height: 1191 },
        A4: { width: 595, height: 842 },
        A5: { width: 420, height: 595 },
        B4: { width: 729, height: 1032 },
        B5: { width: 516, height: 729 }
      };
      const key = (name || '').trim();
      return PAGE_SIZES[key] ?? PAGE_SIZES.A4;
    }

    function getMargin(name: string): number {
      const key = (name || '').trim();
      if (key === 'Small') return 20;
      if (key === 'Large') return 40;
      return 0;
    }

    function getRotationAngle(deg: string): PdfRotationAngle {
      switch ((deg || '').trim()) {
        case '90':
          return PdfRotationAngle.angle90;
        case '180':
          return PdfRotationAngle.angle180;
        case '270':
          return PdfRotationAngle.angle270;
        default:
          return PdfRotationAngle.angle0;
      }
    }

    function readUI() {
      const ps = (document.getElementById('ps') as HTMLSelectElement)?.value ?? 'A4';
      const po = (document.getElementById('po') as HTMLSelectElement)?.value ?? 'Portrait';
      const pm = (document.getElementById('pm') as HTMLSelectElement)?.value ?? 'No margin';
      const pr = (document.getElementById('pr') as HTMLSelectElement)?.value ?? '0';
      const pageCount = parseInt((document.getElementById('pageCount') as HTMLInputElement)?.value ?? '1', 10);
      return { ps, po, pm, pr, pageCount: Math.max(1, pageCount || 1) };
    }

    return {};
  }
});
</script>