<template>
  <div class="control-section">
    <p>
      Click the button to view a PDF document generated by JavaScript PDF Library. Please note
      that Adobe Reader or its equivalent is required to view the resultant document.
    </p>

    <div class="button-section">
      <div id="button-control">
        <div class="row">
          <button id="viewtemplatebtn" class="e-btn">View Template</button>
          <button id="rearrangebtn" class="e-btn">Rearrange Pages</button>
        </div>
      </div>
    </div>

    <div id="action-description" style="margin-top: 10px">
      <p>This sample demonstrates how to rearrange pages from an existing PDF document to make the document meaningful.</p>
    </div>
    <div id="description" style="margin-top: 10px">
      <p>More information about rearrange pages can be found in this documentation <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/pdf-pages#rearranging-pages-in-an-existing-document">section</a>.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import { PdfDocument } from '@syncfusion/ej2-pdf';

export default defineComponent({
  name: 'RearrangePages',
  setup() {
    onMounted(() => {
      const viewBtn = new Button({}, '#viewtemplatebtn');
      const rearrangeBtn = new Button({}, '#rearrangebtn');

      if (rearrangeBtn && rearrangeBtn.element) {
        (rearrangeBtn.element as HTMLButtonElement).onclick = async (): Promise<void> => {
          try {
            const pdfBytes = await readFromPdfResources(templateUrl);
            const pdf = new PdfDocument(pdfBytes as any);
            // Reorder pages: example order [2,0,1]
            (pdf as any).reorderPages([2, 0, 1]);
            pdf.save(outputPdfName);
            pdf.destroy();
          } catch (err) {
            console.error('Rearrange Pages failed:', err);
          }
        };
      }

      if (viewBtn && viewBtn.element) {
        (viewBtn.element as HTMLButtonElement).onclick = async (): Promise<void> => {
          try {
            const pdfBytes = await readFromPdfResources(templateUrl);
            downloadBlob(new Blob([pdfBytes], { type: 'application/pdf' }), 'SyncfusionBrochure.pdf');
          } catch (err) {
            console.error('View Template failed:', err);
          }
        };
      }
    });
    return {};
  }
});

const templateUrl = 'https://cdn.syncfusion.com/content/pdf-resources/syncfusion-brochure.pdf';
const outputPdfName = 'RearrangedPages.pdf';

async function readFromPdfResources(url: string): Promise<Uint8Array> {
  const res = await fetch(url, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  const buf = await res.arrayBuffer();
  return new Uint8Array(buf);
}

function downloadBlob(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
</script>

<style scoped>
  .control-section { padding: 12px; font-size: 14px; }
  .row { display: flex; gap: 12px; }
  .e-btn { width: 150px; text-transform: capitalize; }
  #action-description, #description { margin-top: 10px; }
</style>
