<template>
  <div>
    <div class="control-section">
      <div class="tablediv" style="font-size:14px">
        <div class="rowdiv">
          <div class="celldiv">
            <table width="100%">
              <tbody>
                <tr>
                  <td>
                    Click the button to view a PDF document generated by JavaScript PDF Library. Please note
                    that Adobe Reader or its equivalent is required to view the resultant document.
                  </td>
                </tr>
                <tr>
                  <td align="left">
                    <br />
                    <button id="viewtemplatebtn" class="e-btn" type="button" style="width: 150px; text-transform:capitalize">
                      View Template
                    </button>
                    <button id="topRedactBtn" class="e-btn" type="button"
                      style="width: 150px; text-transform:capitalize; margin-left: 8px">
                      Redact PDF
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div style="font-size:14px; margin-top:16px">
        <div>Use choose file option to select the PDF document and redact the content</div>
        <div class="redact-panel" style="margin-top:8px;">
          <div class="file-row">
          <div class="row">
              <input id="pdfFile" class="file-input" type="file" accept="application/pdf">
              <label for="pdfFile" class="e-btn file-btn">Choose File</label>&nbsp;
              <span id="pdfFileName" class="file-name"> No file chosen</span>
              </div>
            <span id="fileMessage" style="display:none; color:#D22E2E; font-weight:600;" aria-live="polite">
              Choose PDF document to redact
            </span>
          </div>

          <div class="field-grid">
            <div class="field">
              <label for="x">X</label>
              <input type="text" class="e-input" id="x" name="x" value="0" />
            </div>
            <div class="field">
              <label for="y">Y</label>
              <input type="text" class="e-input" id="y" name="y" value="0" />
            </div>
            <div class="field">
              <label for="width">Width</label>
              <input type="text" class="e-input" id="width" name="width" value="200" />
            </div>
            <div class="field">
              <label for="height">Height</label>
              <input type="text" class="e-input" id="height" name="height" value="100" />
            </div>
          </div>

          <div class="actions">
            <button id="uploadRedactBtn" class="e-btn" type="button" style="width: 150px; text-transform:capitalize">
              Redact PDF
            </button>
          </div>
        </div>
      </div>
    </div>

    <div id="action-description">
      <p>This sample demonstrates redact a text from the PDF document. Redaction is a process of permanently removing sensitive or unwanted information from the PDF document.</p>
    </div>
    <div id="description">
      <p>It is also possible to redact shapes and images. More information about the redaction can be found in this documentation <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/redaction">section</a>.</p>
    </div>
  </div>
</template>
<style scoped>
    .redact-panel {
      border: 1px solid #788DB3;
      padding: 12px;
      line-height: 1.4;
    }
    .row {
      display: flex;
      align-items: center;
      margin: 10px 0;
    }
    .control-section .file-input {
      position: absolute;
      width: 1px;
      height: 1px;
      padding: 0;
      margin: -1px;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
      border: 0;
    }
    .file-name {
      color: #6b7280;
    }
    .field-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-row-gap: 14px;
        grid-column-gap: 22px;
        align-items: center;
    }
    .field {
        display: flex;
        align-items: center;
        gap: 12px;
    }
    .field .e-input,
    .field input[type="text"] {
        width: 180px;
        max-width: 100%;
        padding: 8px 10px;
        box-sizing: border-box;
    }
    .field label {
        min-width: 56px;
        font-weight: 500;
    }
    .file-row {
        margin-bottom: 12px;
    }
    .actions {
        margin-top: 16px;
    }
</style>
<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import { PdfDocument } from '@syncfusion/ej2-pdf';
import { PdfRedactor, PdfRedactionRegion } from '@syncfusion/ej2-pdf-data-extract';

export default defineComponent({
  name: 'RedactionPdf',
  setup() {
    onMounted(() => {
      const viewBtn = new Button({}, '#viewtemplatebtn');
      const topRedactBtn = new Button({}, '#topRedactBtn');
      const uploadRedactBtn = new Button({}, '#uploadRedactBtn');

      viewBtn.element.onclick = viewTemplate;
      topRedactBtn.element.onclick = redactPdfFromResource;
      uploadRedactBtn.element.onclick = redactPdfFromUpload;
      // update filename inline when user picks a file via file input
      const pdfFileInput = document.getElementById('pdfFile') as HTMLInputElement | null;
      const pdfFileNameEl = document.getElementById('pdfFileName') as HTMLElement | null;
      if (pdfFileInput && pdfFileNameEl) {
          pdfFileInput.addEventListener('change', () => {
              const f = pdfFileInput.files && pdfFileInput.files[0];
              pdfFileNameEl.textContent = f ? f.name : 'No file chosen';
          });
      }
      (window as any).viewTemplate = viewTemplate;
      (window as any).redactPdfFromResource = redactPdfFromResource;
      (window as any).redactPdfFromUpload = redactPdfFromUpload;
    });

    async function redactPdf(
      pdfBytes: Uint8Array,
      rect: { x: number; y: number; width: number; height: number }
        | Array<{ x: number; y: number; width: number; height: number }>
    ): Promise<void> {
      const bytes = pdfBytes instanceof Uint8Array ? pdfBytes : new Uint8Array(pdfBytes as any);
      const pdf = new PdfDocument(bytes);
      const rects = Array.isArray(rect) ? rect : [rect];
      const redactor = new PdfRedactor(pdf);
      const regions: PdfRedactionRegion[] = rects.map((r) => {
        const region = new PdfRedactionRegion(0, { x: r.x, y: r.y, width: r.width, height: r.height });
        region.fillColor = { r: 0, g: 0, b: 0 };
        return region;
      });
      redactor.add(regions);
      redactor.redactSync();
      pdf.save('Redaction.pdf');
      pdf.destroy();
    }

    const redactPdfFromUpload = (): void => {
      const fileInput = document.getElementById('pdfFile') as HTMLInputElement | null;
      const fileNameSpan = document.getElementById('pdfFileName') as HTMLElement | null;
      const msgSpan = document.getElementById('fileMessage') as HTMLSpanElement | null;
      // update filename display when invoked from button too
      if (fileNameSpan) {
          const f = fileInput?.files?.[0];
          fileNameSpan.textContent = f ? f.name : 'No file chosen';
      }
      if (msgSpan) msgSpan.style.display = 'none';
      const chosenFile = fileInput?.files?.[0];
      if (!chosenFile) {
        if (msgSpan) {
          msgSpan.textContent = 'Choose PDF document to redact';
          msgSpan.style.display = 'inline';
        }
        return;
      }
      const xEl = document.getElementById('x') as HTMLInputElement | null;
      const yEl = document.getElementById('y') as HTMLInputElement | null;
      const wEl = document.getElementById('width') as HTMLInputElement | null;
      const hEl = document.getElementById('height') as HTMLInputElement | null;
      const x = parseFloat(xEl?.value ?? '');
      const y = parseFloat(yEl?.value ?? '');
      const w = parseFloat(wEl?.value ?? '');
      const h = parseFloat(hEl?.value ?? '');
      if ([x, y, w, h].some((v) => isNaN(v))) {
        alert('Please enter valid numeric values for X, Y, Width, and Height.');
        return;
      }
      const reader = new FileReader();
      reader.onload = async (e) => {
        try {
          const buffer = e.target?.result as ArrayBuffer;
          const bytes = new Uint8Array(buffer);
          await redactPdf(bytes, { x, y, width: w, height: h });
        } catch (err) {
          // eslint-disable-next-line no-console
          console.error(err);
          alert('Failed to redact the uploaded PDF.');
        }
      };
      reader.readAsArrayBuffer(chosenFile);
    };

    const viewTemplate = async (): Promise<void> => {
      try {
        const pdfData = await fetchAsUint8Array(input1);
        downloadPdf(pdfData, 'RedactionTemplate.pdf');
      } catch (err) {
        // eslint-disable-next-line no-console
        console.error(err);
        alert('Failed to load the template PDF. Check the file path and server setup.');
      }
    };

    const redactPdfFromResource = async (): Promise<void> => {
      const rects = [
        { x: 70, y: 120, width: 200, height: 80 },
        { x: 400, y: 150, width: 100, height: 30 }
      ];
      try {
        const pdfData = await fetchAsUint8Array(input1);
        await redactPdf(pdfData, rects);
      } catch (err) {
        // eslint-disable-next-line no-console
        console.error(err);
        alert('Failed to redact the resource PDF. Check the file path and server setup.');
      }
    };

    function downloadPdf(bytes: Uint8Array, fileName: string): void {
      const blob = new Blob([bytes], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = fileName;
      a.click();
      URL.revokeObjectURL(url);
    }

    return {};
  }
});

const input1 = 'https://cdn.syncfusion.com/content/pdf-resources/credit_card_statement.pdf';
async function fetchAsUint8Array(url: string): Promise<Uint8Array> {
  const res = await fetch(url, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  const buf = await res.arrayBuffer();
  return new Uint8Array(buf);
}
</script>
