<template>
  <div>
    <div class="control-section">
      <div class="tablediv" style="font-size:14px">
        Click the button to view a PDF document generated by JavaScript PDF Library. Please note
        that Adobe Reader or its equivalent is required to view the resultant document.
      </div>
      <div class="button-section" style="margin-left: 15px; margin-top: 20px;">
        <div id="button-control">
          <div class="row">
            <input id="shapebtn" class="e-btn" value="Generate PDF" style="width: 150px; text-transform:capitalize" />
          </div>
        </div>
      </div>
    </div>

    <div id="action-description">
      This sample demonstrates drawing of <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/shapes">shapes</a> such as Ellipse, Arcs, Polygon, Pie, and Rectangle in the PDF document.
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import { PdfDocument, PdfPage, PdfGraphics, PdfBrush, PdfPen, PdfFontFamily, PdfFontStyle, PdfLineJoin } from '@syncfusion/ej2-pdf';

export default defineComponent({
  name: 'ShapesPdf',
  setup() {
    onMounted(() => {
      const button = new Button({}, '#shapebtn');
      (button.element as HTMLElement).onclick = createPdf;
    });

    function createPdf(): void {
      const doc = new PdfDocument();
      const page: PdfPage = doc.addPage();
      const g: PdfGraphics = page.graphics;

      const headerFont = doc.embedFont(PdfFontFamily.helvetica, 14, PdfFontStyle.bold);
      const pointNum = 16;
      const radius = 100;
      const center = { x: 140, y: 140 };

      // Build polygon points
      const polygonPoints = makeRegularPolygon(center.x, center.y, radius, pointNum);

      // Pens and brushes
      const brownPen = new PdfPen({ r: 165, g: 42, b: 42 }, 10);
      try { (brownPen as any)._lineJoin = PdfLineJoin.round; } catch (e) { /* fallback if private */ }
      const greenBrush = new PdfBrush({ r: 0, g: 128, b: 0 });

      g.drawString('Polygon', headerFont, { x: 50, y: 0, width: 100, height: 100 }, new PdfBrush({ r: 0, g: 0, b: 139 }));
      g.drawPolygon(polygonPoints, brownPen, greenBrush);

      let rect = { x: 20, y: 280, width: 200, height: 200 };
      g.drawString('Pie shape', headerFont, { x: 50, y: 250, width: 100, height: 100 }, new PdfBrush({ r: 0, g: 0, b: 139 }));
      g.drawPie(rect, 180, 60, brownPen, greenBrush);
      g.drawPie(rect, 300, 60, brownPen, greenBrush);
      g.drawPie(rect, 60, 60, brownPen, greenBrush);

      g.drawString('Arcs', headerFont, { x: 330, y: 0, width: 100, height: 100 }, new PdfBrush({ r: 0, g: 0, b: 139 }));
      rect = { x: 310, y: 40, width: 200, height: 200 };
      g.drawArc(rect, 0, 90, new PdfPen({ r: 165, g: 42, b: 42 }, 11));
      g.drawArc({ x: rect.x - 10, y: rect.y, width: rect.width, height: rect.height }, 90, 90, new PdfPen({ r: 0, g: 100, b: 0 }, 11));
      g.drawArc({ x: rect.x - 10, y: rect.y - 10, width: rect.width, height: rect.height }, 180, 90, new PdfPen({ r: 165, g: 42, b: 42 }, 11));
      g.drawArc({ x: rect.x, y: rect.y - 10, width: rect.width, height: rect.height }, 270, 90, new PdfPen({ r: 0, g: 100, b: 0 }, 11));

      rect = { x: 310, y: 280, width: 200, height: 100 };
      g.drawString('Simple Rectangle', headerFont, { x: 310, y: 255, width: 150, height: 100 }, new PdfBrush({ r: 0, g: 0, b: 139 }));
      g.drawRectangle(rect, new PdfPen({ r: 165, g: 42, b: 42 }, 11), new PdfBrush({ r: 0, g: 128, b: 0 }));

      g.drawString('Shape with pagination', headerFont, { x: 300, y: 390, width: 200, height: 100 }, new PdfBrush({ r: 0, g: 0, b: 139 }));
      const brownBrush = new PdfBrush({ r: 165, g: 42, b: 42 });
      const green = new PdfBrush({ r: 0, g: 128, b: 0 });
      // Large ellipse on first page
      g.drawEllipse({ x: 300, y: 450, width: 160, height: 1100 }, brownBrush);
      g.drawEllipse({ x: 320, y: 480, width: 160, height: 1100 }, green);

      const page2 = doc.addPage();
      const g2 = page2.graphics;
      g2.drawEllipse({ x: 300, y: -480, width: 160, height: 1100 }, brownBrush);
      g2.drawEllipse({ x: 320, y: -450, width: 160, height: 1100 }, green);

      g2.drawString('Transparent Rectangles', headerFont, { x: 50, y: 80, width: 200, height: 100 }, new PdfBrush({ r: 0, g: 0, b: 139 }));
      let r = { x: 10, y: 150, width: 100, height: 100 };
      let p = new PdfPen({ r: 0, g: 0, b: 0 }, 1);
      let b: PdfBrush = new PdfBrush({ r: 0, g: 100, b: 0 });
      g2.drawRectangle(r, p, b);
      r = { x: r.x + 20, y: r.y + 20, width: r.width, height: r.height };
      p = new PdfPen({ r: 165, g: 42, b: 42 }, 1);
      b = new PdfBrush({ r: 165, g: 42, b: 42 });
      g2.setTransparency(0.7);
      g2.drawRectangle(r, p, b);
      r = { x: r.x + 20, y: r.y + 20, width: r.width, height: r.height };
      g2.setTransparency(0.5);
      g2.drawRectangle(r, p, new PdfBrush({ r: 0, g: 100, b: 0 }));
      r = { x: r.x + 20, y: r.y + 20, width: r.width, height: r.height };
      p = new PdfPen({ r: 0, g: 0, b: 255 }, 1);
      b = new PdfBrush({ r: 128, g: 128, b: 128 });
      g2.setTransparency(0.25);
      g2.drawRectangle(r, p, b);
      r = { x: r.x + 20, y: r.y + 20, width: r.width, height: r.height };
      p = new PdfPen({ r: 0, g: 0, b: 0 }, 1);
      b = new PdfBrush({ r: 0, g: 128, b: 0 });
      g2.setTransparency(0.1);
      g2.drawRectangle(r, p, b);

      // Save and download
      doc.save('Shapes.pdf');
      doc.destroy();
    }

    function makeRegularPolygon(cx: number, cy: number, r: number, pointNum: number): Array<{ x: number; y: number }> {
      const pts: Array<{ x: number; y: number }> = [];
      const f = (360.0 / pointNum) * Math.PI / 180.0;
      for (let i = 0; i < pointNum; i++) {
        const theta = i * f;
        pts.push({ x: Math.cos(theta) * r + cx, y: Math.sin(theta) * r + cy });
      }
      return pts;
    }

    return {};
  }
});
</script>
