<template>
  <div class="control-section">
    <div class="pdf-container">
      <div class="file-upload">
        <input type="file" id="fileUpload" accept=".pdf,application/pdf" />
        <label for="fileUpload" class="choose-file-btn"><strong>Choose File</strong></label>
        <span id="fileName" aria-live="polite" class="file-name">SplitPDF.pdf</span>
      </div>

      <div>
        <label class="split-label" style="margin-bottom:20px; display:block;">Select the below options to split by:</label>
        <div class="radio-group" role="radiogroup" aria-label="Split options">
          <label class="radio-option">
            <input type="radio" id="fixedRange" name="splitOption" value="fixed" checked />
            Fixed Range
          </label>
          <label class="radio-option">
            <input type="radio" id="fileCount" name="splitOption" value="fileCount" />
            File Count
          </label>
          <label class="radio-option">
            <input type="radio" id="pageCount" name="splitOption" value="pageCount" />
            Page Count
          </label>
        </div>
      </div>

      <div id="fileCountSection" style="display:none;">
        <label for="fileCountInput"><strong>Number of files</strong></label>
        <div class="filecount-group">
          <input type="text" id="fileCountInput" value="2" min="1" inputmode="numeric" />
        </div>
      </div>

      <div id="pageCountSection" style="display:none;">
        <label for="pagesPerFileInput"><strong>Pages per file</strong></label>
        <div class="pagecount-group">
          <input type="text" id="pagesPerFileInput" value="1" min="1" inputmode="numeric" />
        </div>
      </div>

      <div id="rangeSection" style="display:none;">
        <label class="split-label" style="margin-bottom:20px; display:block;">Enter page ranges to split:</label>
        <div class="range-group">
          <label for="fromPage">From</label>
          <input type="text" id="fromPage" value="1" min="1" inputmode="numeric" />
          <label for="toPage">To</label>
          <input type="text" id="toPage" value="1" min="1" inputmode="numeric" />
        </div>
      </div>
      <div style="margin-top: 10px;">
        <p>
          Click the button to view a PDF document generated by JavaScript PDF Library. Please note
          that Adobe Reader or its equivalent is required to view the resultant document.
        </p>
      </div>
      <div>
        <button id="splitBtn" class="e-btn" type="button">Split PDF</button>
      </div>
    </div>
    <div id="action-description">
      <p>
        This sample demonstrates how to split the pages of a PDF into multiple PDF documents.
      </p>
    </div>
    <div id="description">
      <p>This feature will be used to split the necessary pages from the PDF document, divide a large-sized PDF into smaller ones. More information about the split PDF documents can be found in this documentation <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/split-documents">section</a>.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import { NumericTextBox } from '@syncfusion/ej2-inputs';
import { PdfDocument } from '@syncfusion/ej2-pdf';

const DEFAULT_PDF_NAME = 'pdf-succinctly.pdf';
const DEFAULT_PDF_URL = 'https://cdn.syncfusion.com/content/pdf-resources/pdf-succinctly.pdf';

export default defineComponent({
  name: 'SplitPdf',
  setup() {
    onMounted(() => {
      const splitBtnSf = new Button({}, '#splitBtn');

      const fileInput = document.getElementById('fileUpload') as HTMLInputElement | null;
      const fileNameSpan = document.getElementById('fileName') as HTMLSpanElement | null;
      const fixedRangeRadio = document.getElementById('fixedRange') as HTMLInputElement | null;
      const fileCountRadio = document.getElementById('fileCount') as HTMLInputElement | null;
      const pageCountRadio = document.getElementById('pageCount') as HTMLInputElement | null;
      const rangeSection = document.getElementById('rangeSection') as HTMLDivElement | null;
      const fileCountSection = document.getElementById('fileCountSection') as HTMLDivElement | null;
      const pageCountSection = document.getElementById('pageCountSection') as HTMLDivElement | null;

      // EJ2 NumericTextBox instances (initialized when section becomes visible)
      let fromNumeric: NumericTextBox | null = null;
      let toNumeric: NumericTextBox | null = null;
      let fileCountNumeric: NumericTextBox | null = null;
      let pagesPerFileNumeric: NumericTextBox | null = null;

      if (fileNameSpan) fileNameSpan.textContent = DEFAULT_PDF_NAME;
      if (fileInput && fileNameSpan) {
        fileInput.addEventListener('change', () => {
          fileNameSpan.textContent = fileInput.files?.[0]?.name || DEFAULT_PDF_NAME;
        });
      }

      function initRangeNumerics(): void {
        try {
          if (!fromNumeric) {
            fromNumeric = new NumericTextBox({ min: 1, step: 1, format: 'n0', width: '120px', placeholder: 'From', value: 1 }, '#fromPage');
          }
          if (!toNumeric) {
            toNumeric = new NumericTextBox({ min: 1, step: 1, format: 'n0', width: '120px', placeholder: 'To', value: 1 }, '#toPage');
          }
        } catch {
          // Safe-guard: ignore if EJ2 inputs are unavailable
        }
      }

      function initFileCountNumeric(): void {
        try {
          if (!fileCountNumeric) {
            fileCountNumeric = new NumericTextBox({ min: 1, step: 1, format: 'n0', width: '80px', value: 2 }, '#fileCountInput');
          }
        } catch {
          // ignore
        }
      }

      function initPagesPerFileNumeric(): void {
        try {
          if (!pagesPerFileNumeric) {
            pagesPerFileNumeric = new NumericTextBox({ min: 1, step: 1, format: 'n0', width: '80px', value: 1 }, '#pagesPerFileInput');
          }
        } catch {
          // ignore
        }
      }

      function updateVisibility(): void {
        const selected = (document.querySelector('input[name="splitOption"]:checked') as HTMLInputElement | null)?.value;
        if (rangeSection) {
          const show = selected === 'fixed';
          rangeSection.style.display = show ? 'block' : 'none';
          if (show) initRangeNumerics();
        }
        if (fileCountSection) fileCountSection.style.display = selected === 'fileCount' ? 'block' : 'none';
        if (pageCountSection) pageCountSection.style.display = selected === 'pageCount' ? 'block' : 'none';
        if (fileCountSection && selected === 'fileCount') initFileCountNumeric();
        if (pageCountSection && selected === 'pageCount') initPagesPerFileNumeric();
      }

      fixedRangeRadio?.addEventListener('change', updateVisibility);
      fileCountRadio?.addEventListener('change', updateVisibility);
      pageCountRadio?.addEventListener('change', updateVisibility);
      updateVisibility();

      splitBtnSf.element.onclick = splitPdf;

      async function splitPdf(): Promise<void> {
        try {
          const bytes = await getInputPdfBytes();
          const pdf = new PdfDocument(bytes as any);
          (pdf as any).splitEvent = (_sender: unknown, args: { index: number; pdfData: Uint8Array }) => {
            const part = new PdfDocument(args.pdfData as any);
            part.save(`SplittedDoc_${args.index + 1}.pdf`);
            part.destroy();
          };
          const total = (pdf as any).pageCount || 0;
          if (total <= 0) {
            pdf.destroy();
            alert('The input PDF has no pages.');
            return;
          }
          const fixedRangeRadioEl = document.getElementById('fixedRange') as HTMLInputElement | null;
          const fileCountRadioEl = document.getElementById('fileCount') as HTMLInputElement | null;
          const pageCountRadioEl = document.getElementById('pageCount') as HTMLInputElement | null;
          if (fixedRangeRadioEl?.checked) {
            const fromEl = document.getElementById('fromPage') as HTMLInputElement | null;
            const toEl = document.getElementById('toPage') as HTMLInputElement | null;
            const from = Number(fromNumeric?.value ?? parseInt(fromEl?.value ?? '1', 10));
            const to = Number(toNumeric?.value ?? parseInt(toEl?.value ?? '1', 10));
            if (isNaN(from) || isNaN(to) || from < 1 || to < from || to > total) {
              alert(`Please enter a valid page range between 1 and ${total}.`);
              pdf.destroy();
              return;
            }
            const startIndex = from - 1;
            const endIndex = to - 1;
            (pdf as any).splitByPageRanges([[startIndex, endIndex]]);
          } else if (fileCountRadioEl?.checked) {
            const fileCountEl = document.getElementById('fileCountInput') as HTMLInputElement | null;
            const n = Math.max(1, Number(fileCountNumeric?.value ?? parseInt(fileCountEl?.value ?? '2', 10)));
            const ranges = buildRangesForFileCount(total, n);
            (pdf as any).splitByPageRanges(ranges);
          } else if (pageCountRadioEl?.checked) {
            const pagesPerEl = document.getElementById('pagesPerFileInput') as HTMLInputElement | null;
            const per = Math.max(1, Number(pagesPerFileNumeric?.value ?? parseInt(pagesPerEl?.value ?? '1', 10)));
            (pdf as any).splitByFixedNumber(per);
          }
          pdf.destroy();
        } catch (err: any) {
          console.error(err);
          alert(err?.message || 'Failed to split PDF.');
        }
      }

      async function getInputPdfBytes(): Promise<Uint8Array> {
        const fileInput = document.getElementById('fileUpload') as HTMLInputElement | null;
        const chosen = fileInput?.files?.[0];
        if (chosen) {
          const buf = await chosen.arrayBuffer();
          return new Uint8Array(buf);
        }
        const res = await fetch(DEFAULT_PDF_URL, { cache: 'no-cache' });
        if (!res.ok) throw new Error(`Failed to fetch default PDF: ${res.status} ${res.statusText}`);
        const buf = await res.arrayBuffer();
        return new Uint8Array(buf);
      }

      function buildRangesForFileCount(totalPages: number, numberOfFiles: number): Array<[number, number]> {
        const ranges: Array<[number, number]> = [];
        const per = Math.ceil(totalPages / Math.max(1, numberOfFiles));
        let start = 0;
        while (start < totalPages) {
          const end = Math.min(start + per - 1, totalPages - 1);
          ranges.push([start, end]);
          start = end + 1;
        }
        return ranges;
      }
    });
    return {};
  }
});
</script>

<style scoped>
  .control-section { font-size: 14px; padding: 15px; }
  .pdf-container { display: flex; flex-direction: column; gap: 20px; max-width: none; }
  .file-upload { display: flex; align-items: center; gap: 12px; }
  .file-upload input[type="file"] { position: absolute !important; left: -9999px !important; width: 0 !important; height: 0 !important; opacity: 0 !important; }
  .choose-file-btn { display: inline-block; padding: 6px 12px; border: 1px solid #ccc; border-radius: 4px; background: #fff; cursor: pointer; }
  .radio-group { display: flex; align-items: center; gap: 28px; margin-top: 8px; }
  .radio-option { display: inline-flex; align-items: center; gap: 10px; line-height: 1.2; white-space: nowrap; }
  .radio-option input[type="radio"] { margin: 0; vertical-align: middle; }
  .pdf-container label { display: block; margin-bottom: 5px; }
  .range-group, .filecount-group, .pagecount-group { display: inline-flex; align-items: center; gap: 12px; white-space: nowrap; }
  .range-group input { width: 120px; }
  .filecount-group input, .pagecount-group input { width: 80px; }
  .e-btn { width: 150px; text-transform: capitalize; }
  .file-name { color: #6b7280; }
  .split-label {
    margin-bottom: 20px;
  }
</style>
