<template>
  <div class="control-section">
    <div class="card">
      <div class="row">
        <label class="row__label" for="pdfFile">Choose PDF</label>
        <input id="pdfFile" class="file-input" type="file" accept="application/pdf" />
        <label for="pdfFile" class="e-btn file-btn">Choose File</label>
        <span id="pdfFileName" class="file-name">HTTP Succinctly.pdf</span>
      </div>

      <div class="row">
        <label class="row__label" for="stampText">Stamping Text</label>
        <input id="stampText" type="text" class="e-input" style="width:420px" value="Created using Syncfusion PDF library" />
      </div>

      <div class="row">
        <label class="row__label" for="transparency">Set Transparency</label>
        <select id="transparency" class="e-input" style="width:120px;">
          <option value="0.10">10</option>
          <option value="0.15">15</option>
          <option value="0.20">20</option>
          <option value="0.25" selected>25</option>
          <option value="0.30">30</option>
          <option value="0.35">35</option>
          <option value="0.40">40</option>
          <option value="0.50">50</option>
        </select>
        <span style="color:#6b7280;">%</span>
      </div>

      <div class="row">
        <input id="useImage" type="checkbox" />
        <label for="useImage" style="font-weight:600; margin-top:10px;">Image watermark</label>
      </div>

      <div id="imageRow" class="row" style="display:none;">
        <label class="row__label" for="imgFile">Choose Image</label>
        <input id="imgFile" class="file-input" type="file" accept="image/*" />
        <label for="imgFile" class="e-btn file-btn">Choose File</label>
        <span id="imgFileName" class="file-name">No file chosen</span>
      </div>

      <div id="alertArea" style="display:none; margin-top:8px; color:#b91c1c; font-weight:600;"></div>

      <br />
      <div>
        <p class="description">
          Click the button to view a PDF document generated by JavaScript PDF Library. Please note that Adobe Reader or its
          equivalent is required to view the resultant document.
        </p>
      </div>
      <div style="margin-top:16px;">
        <button id="watermarkBtn" class="e-btn" type="button">Watermark PDF</button>
      </div>
    </div>
    <div id="action-description">
      <p>
        This sample demonstrates how to stamp an existing PDF document using text. The JavaScript PDF library supports watermarking both text and images in the PDF document.
      </p>
    </div>
    <div id="description">
      <p>This feature can be used to stamp the PDF document for draft, confidential, review purpose only, company logo, copyright notice, and more. More information about the watermark can be found in this documentation <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/watermarks">section</a>.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import { DropDownList } from '@syncfusion/ej2-dropdowns';
import { PdfDocument, PdfFontFamily, PdfFontStyle, PdfBrush, PdfBitmap } from '@syncfusion/ej2-pdf';

const defaultPdfName = 'http-succinctly.pdf';
const input1 = 'https://cdn.syncfusion.com/content/pdf-resources/http-succintly.pdf';
const defaultStampText = 'Created using Syncfusion PDF library';
const defaultTransparency = 0.25;

export default defineComponent({
  name: 'WatermarkPdf',
  setup() {
    let transparencyDdl: DropDownList | null = null;
    onMounted(() => {
      const watermarkBtn = new Button({}, '#watermarkBtn');
      const pdfFileEl = document.getElementById('pdfFile') as HTMLInputElement | null;
      const pdfNameEl = document.getElementById('pdfFileName') as HTMLSpanElement | null;
      const useImageEl = document.getElementById('useImage') as HTMLInputElement | null;
      const imageRow = document.getElementById('imageRow') as HTMLDivElement | null;
      const imgFileEl = document.getElementById('imgFile') as HTMLInputElement | null;
      const imgNameEl = document.getElementById('imgFileName') as HTMLSpanElement | null;

      if (pdfNameEl) pdfNameEl.textContent = defaultPdfName;
      if (imgNameEl) imgNameEl.textContent = 'No file chosen';

      if (pdfFileEl && pdfNameEl) {
        pdfFileEl.addEventListener('change', () => {
          const f = pdfFileEl.files?.[0];
          pdfNameEl.textContent = f ? f.name : defaultPdfName;
        });
      }
      if (useImageEl && imageRow) {
        useImageEl.addEventListener('change', () => {
          imageRow.style.display = useImageEl.checked ? 'flex' : 'none';
        });
      }
      if (imgFileEl && imgNameEl) {
        imgFileEl.addEventListener('change', () => {
          const f = imgFileEl.files?.[0];
          imgNameEl.textContent = f ? f.name : 'No file chosen';
        });
      }

      // Initialize EJ2 DropDownList on the transparency select to match cshtml
      try {
        transparencyDdl = new DropDownList({ width: '120px', value: String(defaultTransparency) }, '#transparency');
      } catch {
        // Ignore if EJ2 dropdowns bundle isn't available; fallback to native select
      }

      if (watermarkBtn && watermarkBtn.element) {
        (watermarkBtn.element as HTMLButtonElement).onclick = onClickWatermarkBtn;
      }
    });

    async function createWatermarkedPdf(): Promise<void> {
      const { userPdf, userImg, stampText, transparency, useImage } = readUIValues();
      const pdfNameEl = document.getElementById('pdfFileName') as HTMLSpanElement | null;
      if (pdfNameEl) pdfNameEl.textContent = userPdf ? userPdf.name : defaultPdfName;

      const pdfBytes = await getPdfBytesOrDefault(userPdf);
      const imageBytes = useImage && userImg ? await getImageBytes(userImg) : null;

      const pdf = new PdfDocument(pdfBytes as any);

      const maxWidth = 600;
      let font = pdf.embedFont(PdfFontFamily.helvetica, 36, PdfFontStyle.regular);
      let textSize = font.measureString(stampText);
      while (textSize.width > maxWidth && (font as any).size > 6) {
        font = pdf.embedFont(PdfFontFamily.helvetica, (font as any).size - 1, PdfFontStyle.regular);
        textSize = font.measureString(stampText);
      }

      const pageCount = (pdf as any).pageCount || 0;

      if (stampText && stampText.trim()) {
        for (let i = 0; i < pageCount; i++) {
          const page = (pdf as any).getPage(i);
          const g = page.graphics;
          g.save();
          g.setTransparency(transparency);
          const width = g.clientSize.width;
          const height = g.clientSize.height;
          g.translateTransform({ x: width / 2, y: height / 2 });
          g.rotateTransform(-45);
          const brush = new PdfBrush({ r: 255, g: 0, b: 0 });
          g.drawString(stampText, font, { x: -(textSize.width / 2), y: -(textSize.height / 2), width, height }, brush);
          g.restore();
        }
      }

      if (useImage && imageBytes) {
        const bmp = new PdfBitmap(imageBytes as any);
        for (let i = 0; i < pageCount; i++) {
          const page = (pdf as any).getPage(i);
          const g = page.graphics;
          g.setTransparency(transparency);
          const width = g.clientSize.width;
          const height = g.clientSize.height;
          g.drawImage(bmp, { x: 0, y: 0, width, height });
        }
      }

      pdf.save('Watermarked.pdf');
      pdf.destroy();
    }

    function readUIValues() {
      const pdfFileEl = document.getElementById('pdfFile') as HTMLInputElement | null;
      const imgFileEl = document.getElementById('imgFile') as HTMLInputElement | null;
      const stampTextEl = document.getElementById('stampText') as HTMLInputElement | null;
      const transparencyEl = document.getElementById('transparency') as HTMLSelectElement | null;
      const useImageEl = document.getElementById('useImage') as HTMLInputElement | null;
      const stampText = (stampTextEl?.value || defaultStampText).trim();
      const transparencyRaw = String((transparencyDdl as any)?.value ?? transparencyEl?.value ?? String(defaultTransparency));
      const transparency = parseFloat(transparencyRaw) || defaultTransparency;
      const useImage = !!useImageEl?.checked;
      const userPdf = pdfFileEl?.files?.[0] || null;
      const userImg = imgFileEl?.files?.[0] || null;
      return { userPdf, userImg, stampText, transparency, useImage };
    }

    function showAlert(msg: string) {
      const alertArea = document.getElementById('alertArea') as HTMLDivElement | null;
      if (!alertArea) return;
      alertArea.textContent = msg;
      alertArea.style.display = 'block';
    }

    function clearAlert() {
      const alertArea = document.getElementById('alertArea') as HTMLDivElement | null;
      if (!alertArea) return;
      alertArea.textContent = '';
      alertArea.style.display = 'none';
    }

    function onClickWatermarkBtn(): void {
      clearAlert();
      const { useImage, userImg, stampText } = readUIValues();
      if (useImage && !userImg) {
        showAlert('Please select a valid image file to add an image watermark.');
        return;
      }
      if (!useImage && (!stampText || !stampText.trim())) {
        showAlert('Please enter stamping text or enable image watermark.');
        return;
      }
      createWatermarkedPdf().catch((err) => {
        console.error(err);
        showAlert('Failed to process the PDF. See console for details.');
      });
    }

    async function getPdfBytesOrDefault(userPdf: File | null): Promise<Uint8Array> {
      if (userPdf) {
        const buf = await userPdf.arrayBuffer();
        const bytes = new Uint8Array(buf);
        const head = new TextDecoder('ascii').decode(bytes.slice(0, 5));
        if (head !== '%PDF-') throw new Error('Selected file is not a valid PDF.');
        return bytes;
      } else {
        const res = await fetch(input1);
        if (!res.ok) throw new Error(`Failed to fetch default PDF: ${res.status} ${res.statusText}`);
        const buf = await res.arrayBuffer();
        const bytes = new Uint8Array(buf);
        const head = new TextDecoder('ascii').decode(bytes.slice(0, 5));
        if (head !== '%PDF-') throw new Error('Default PDF is not valid.');
        return bytes;
      }
    }

    async function getImageBytes(userImg: File): Promise<Uint8Array> {
      const buf = await userImg.arrayBuffer();
      return new Uint8Array(buf);
    }

    return {};
  }
});
</script>

<style scoped>
  .row { display: flex; align-items: center; gap: 10px; margin: 10px 0; }
  .row__label { min-width: 140px; font-weight: 600; }
  .control-section .file-input { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); border: 0; }
  .file-name { color: #6b7280; }
  .card { padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; max-width: none }
  .e-btn.file-btn { margin-left: 8px; }
</style>
